# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2

before_install:
- composer install --dev

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- ./vendor/bin/php-coveralls -v
